zVector VA, VAC, VMSL and VS instruction corrections for Windows.
Commit 1618183 caused compile errors on Windows, for example:
error C2440: 'type cast' : cannot convert from 'QW' to 'U128'