autoconf/hercules.m4: fix compiling error w/ modern C duing configure
1. withoug "--tag", libtool will:
     libtool:   error: specify a tag with '--tag'
     libtool: compile: unable to infer tagged configuration
2. without "extern ...", compile will:
     error: implicit declaration of function 'getopt'
     error: implicit declaration of function 'test1'

both will cause false postive of feature test, i.e.,
"checking whether getopt wrapper kludge is necessary" report yes always
then config.h always has "#define NEED_GETOPT_WRAPPER 1".

Signed-off-by: Z. Liu <zhixu.liu@gmail.com>